# Generated by Django 4.1.4 on 2022-12-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='num',
            field=models.BigIntegerField(blank=True),
        ),
    ]
