# Generated by Django 4.1.4 on 2023-01-14 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0007_rename_location_restaurant_adresse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='name',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='service1',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='service2',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='account',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='services',
            field=models.CharField(default='Livraison', max_length=250),
            preserve_default=False,
        ),
    ]
