# Generated by Django 4.1.4 on 2022-12-19 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='location',
            new_name='location2',
        ),
        migrations.AddField(
            model_name='product',
            name='location1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source', to='restaurants.restaurant'),
        ),
    ]
