# Generated by Django 4.1.4 on 2022-12-19 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_restaurant_num'),
        ('supermarcher', '0001_initial'),
        ('store', '0002_rename_location_product_location2_product_location1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='location1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source', to='restaurants.restaurant'),
        ),
        migrations.AlterField(
            model_name='product',
            name='location2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source', to='supermarcher.supermarket'),
        ),
    ]
