# Generated by Django 4.1.4 on 2022-12-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_image_link_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_link',
            field=models.CharField(blank=True, default='', max_length=700000, null=True),
        ),
    ]
