# Generated by Django 4.1.4 on 2022-12-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_product_image_link_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_link',
            field=models.ImageField(blank=True, upload_to='products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products'),
        ),
    ]
