# Generated by Django 4.1.4 on 2022-12-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_image_link_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_link',
            field=models.CharField(blank=True, default='', max_length=7000000),
        ),
    ]
