# Generated by Django 4.1.4 on 2022-12-20 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopp_cart',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopp_cart',
            name='ordered_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='shopp_cart',
            name='article',
        ),
        migrations.AlterField(
            model_name='shopp_cart',
            name='quantite',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('ordered', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='store.product')),
            ],
        ),
        migrations.AddField(
            model_name='shopp_cart',
            name='article',
            field=models.ManyToManyField(to='store.articles'),
        ),
    ]
