# Generated by Django 4.1.4 on 2023-01-14 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_shopp_cart_ordered_shopp_cart_ordered_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='location1',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='product',
            name='location2',
        ),
    ]
