# Generated by Django 4.1.4 on 2022-12-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuperMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('rating', models.FloatField(default=0.0)),
                ('h_open', models.TimeField()),
                ('h_close', models.TimeField()),
                ('image', models.ImageField(upload_to='restaurants')),
            ],
        ),
    ]
