# Generated by Django 4.1.4 on 2022-12-20 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0002_emailuser_delete_shopper'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailUser',
            new_name='Shopper',
        ),
    ]
