# Generated by Django 4.1.4 on 2023-01-14 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_alter_shopper_managers_remove_shopper_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopper',
            options={},
        ),
        migrations.RemoveField(
            model_name='shopper',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='shopper',
            name='email',
        ),
        migrations.RemoveField(
            model_name='shopper',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='shopper',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='shopper',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='shopper',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='shopper',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='shopper',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='shopper',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='shopper',
            name='password',
        ),
        migrations.RemoveField(
            model_name='shopper',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='shopper',
            name='username',
        ),
        migrations.AddField(
            model_name='shopper',
            name='Quartier',
            field=models.CharField(default='bibongbidoum', max_length=75),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopper',
            name='account',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopper',
            name='ville',
            field=models.CharField(default='yaounde', max_length=50),
            preserve_default=False,
        ),
    ]
