# Generated by Django 4.1.4 on 2022-12-21 05:45

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_emailuser_shopper'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopper',
            name='phone',
            field=phone_field.models.PhoneField(default='0000000', help_text='Contact phone number', max_length=31, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shopper',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
