# Generated by Django 4.1.4 on 2022-12-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_shopper_phone_alter_shopper_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopper',
            name='phone',
        ),
        migrations.AlterField(
            model_name='shopper',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
